config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  
  resources :users, only: [:show, :edit, :update]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  
  attachment :image
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  attachment :profile_image
  has_many :posts, dependent: :destroy
  
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 10 }, format: { with: /\A[a-zA-Z0-9]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @photo = @post.photos.build
  end
  
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to user_path(current_user)
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:body, photos_attributes: [:image])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_current_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @posts = current_user.posts
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end
  
  def set_current_user
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.slim
.main
  .main-content
    p.main-comment 
      | エキ 
      i.fas.fa-subway
      |  ベン
    span 駅と弁を投稿してシェアするサイト

app/views/layouts/_footer.html.slim
.container
  .row
    .col-6.footer-top
      p
        | エキ 
        i.fas.fa-subway
        |  ベン
    .col-6.footer-menu
      ul.list-unstyled.p-0
        -if user_signed_in?
          li
            = link_to "マイページ", user_path(current_user.id), {class: "link"}
          li
            = link_to "投稿", new_post_path, {class: "link"}
          li
            = link_to "タイムライン", posts_path, {class: "link"}
          li
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        -else
          li
            = link_to "トップ", root_path, {class: "link"}
          li
            = link_to "タイムライン", posts_path, {class: "link"}
          li
            = link_to "新規登録", new_user_registration_path, {class: "link"}
          li
            = link_to "ログイン", new_user_session_path, {class: "link"}

app/views/layouts/_header.html.slim
.shadow-sm
  nav.navbar.navbar-expand-lg.navbar-light
    .container
      button.navbar-toggler  type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"
        | Menu
      .collapse.navbar-collapse.justify-content-center id="navbarNavDropdown"
        ul.navbar-nav.ml-auto.text-right
        -if user_signed_in?
          li.nav-item
            = link_to "マイページ", user_path(current_user.id), {class: "link"}
          li.nav-item
            = link_to "投稿", new_post_path, {class: "link"}
          li.nav-item
            = link_to "タイムライン", posts_path, {class: "link"}
          li.nav-item
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        -else
          li.nav-item
            = link_to "トップ", root_path, {class: "link"}
          li.nav-item
            = link_to "タイムライン", posts_path, {class: "link"}
          li.nav-item
            = link_to "新規登録", new_user_registration_path, {class: "link"}
          li.nav-item
            = link_to "ログイン", new_user_session_path, {class: "link"}

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | EkiBen
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      == render 'layouts/header'
    main
      = yield
    footer
      == render 'layouts/footer'  

app/views/posts/edit.html.slim
p 投稿
= form_with model:@post, local: true do |f|
  = f.text_area :body
  br
  = f.submit "投稿"

app/views/posts/index.html.slim
div.time-line.container.mt-3
  - @posts.each do |post|
    .post
      .row.post-user
        .profile-img-container 
          = attachment_image_tag post.user, :profile_image, fallback: "no_image.jpg"
        .name
          = post.user.name
      div
        = link_to "#{post.body}", post_path(post.id)

app/views/posts/new.html.slim
p 投稿フォーム
= form_with model:@post, local: true do |f|
  = f.text_area :body
  br
  = f.submit "投稿"

app/views/posts/show.html.slim
= @post.body

app/views/users/edit.html.slim
h1 ユーザー情報編集
= form_with model:@user, local: true do |f|
  div 
    = f.label :name
    = f.text_field :name, autofocus: true, autocomplete: "name"
  div
    = f.label :email
    = f.text_field :email, autocomplete: "email"
  div
    = f.attachment_field :profile_image, placeholder: "プロフィール画像"
  div
    = f.submit "変更を保存"

app/views/users/show.html.slim
h1 マイページ
.profile-img-container 
  = attachment_image_tag @user, :profile_image, fallback: "no_image.jpg"
div
  span ユーザー名:
  = @user.name
= link_to "ユーザー情報編集", edit_user_path(current_user.id)
div
  p 投稿
  - @posts.each do |post|
    div
      = post.body
      = link_to "編集", edit_post_path(post)
      | /
      = link_to "削除", post_path(post.id), method: :delete